namespace Paftax.Pafta.Shared.Enums
{
    public enum TagType
    {
        RoomTag,
        AreaTag,
        SpaceTag,
        GenericTag,
        FloorTag,
        CeilingTag,
        WallTag,
        DoorTag,
        WindowTag,
        FurnitureTag,
        CurtainPanelTag,
        DetailItemTag,
        FurnitureSystemTag,
        CaseworkTag,
        PlumbingFixtureTag,
        ElectricalFixtureTag,
        MechanicalEquipmentTag,
        SpecialtyEquipmentTag,
        LightingFixtureTag,
        StructuralFramingTag,
        StructuralColumnTag,
        RailingTag,
        MassTag,
    }
}
